/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch reviews for an app, compute metrics + NLP insights, persist. */
        post: operations["collect_api_v1_reviews_collect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{app_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rating metrics for a previously collected app. */
        get: operations["get_metrics_api_v1_reviews__app_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{app_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sentiment + themes + actionable insights for a previously collected app. */
        get: operations["get_insights_api_v1_reviews__app_id__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{app_id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Raw collected reviews. Returns JSON by default, CSV when ?format=csv. */
        get: operations["get_raw_api_v1_reviews__app_id__raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CollectRequest
         * @example {
         *       "app_id": 324684580,
         *       "country": "us"
         *     }
         */
        CollectRequest: {
            /**
             * App Id
             * @description Apple App Store numeric app id
             */
            app_id: number;
            /**
             * Country
             * @description ISO-3166-1 alpha-2 country code (case-insensitive)
             */
            country: string;
            /**
             * Limit
             * @description Max reviews to fetch (Apple caps around 500)
             * @default 100
             */
            limit: number;
        };
        /** CollectResponse */
        CollectResponse: {
            /** App Id */
            app_id: number;
            /** Country */
            country: string;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
            /** Review Count */
            review_count: number;
            metrics: components["schemas"]["Metrics"];
            insights: components["schemas"]["InsightsReport"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Insight
         * @description An actionable suggestion derived from a theme.
         */
        Insight: {
            /** Title */
            title: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "medium" | "high";
            /** Evidence Count */
            evidence_count: number;
            /** Theme Id */
            theme_id?: number | null;
            /** Suggestion */
            suggestion: string;
        };
        /**
         * InsightsReport
         * @description End-to-end NLP output: sentiment + themes + suggestions.
         */
        InsightsReport: {
            sentiment_breakdown: components["schemas"]["SentimentBreakdown"];
            /** Themes */
            themes: components["schemas"]["Theme"][];
            /** Insights */
            insights: components["schemas"]["Insight"][];
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** App Id */
            app_id: number;
            /** Country */
            country: string;
            /**
             * Last Collected At
             * Format: date-time
             */
            last_collected_at: string;
            insights: components["schemas"]["InsightsReport"];
        };
        /**
         * Metrics
         * @description Aggregated rating statistics for a collected review set.
         */
        Metrics: {
            /** Total Reviews */
            total_reviews: number;
            /** Average Rating */
            average_rating: number;
            /**
             * Distribution
             * @description Always 5 entries, one per star, sorted 1→5.
             */
            distribution: components["schemas"]["RatingBucket"][];
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** App Id */
            app_id: number;
            /** Country */
            country: string;
            /**
             * Last Collected At
             * Format: date-time
             */
            last_collected_at: string;
            metrics: components["schemas"]["Metrics"];
        };
        /**
         * RatingBucket
         * @description Count and share of reviews at a given star rating.
         */
        RatingBucket: {
            /** Rating */
            rating: number;
            /** Count */
            count: number;
            /** Percentage */
            percentage: number;
        };
        /**
         * SentimentBreakdown
         * @description Aggregated sentiment counts and shares across all reviews.
         */
        SentimentBreakdown: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Percentages */
            percentages: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /**
         * SentimentClass
         * @enum {string}
         */
        SentimentClass: "very_negative" | "negative" | "neutral" | "positive" | "very_positive";
        /**
         * Theme
         * @description A cluster of related negative reviews (derived from BERTopic).
         */
        Theme: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Keywords */
            keywords: string[];
            /** Review Ids */
            review_ids: string[];
            /** Share Of Negatives */
            share_of_negatives: number;
            /** Average Rating */
            average_rating: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    collect_api_v1_reviews_collect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_v1_reviews__app_id__metrics_get: {
        parameters: {
            query?: {
                /** @description ISO 3166-1 alpha-2 country code */
                country?: string;
            };
            header?: never;
            path: {
                /** @description Apple App Store numeric app id */
                app_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_insights_api_v1_reviews__app_id__insights_get: {
        parameters: {
            query?: {
                /** @description ISO 3166-1 alpha-2 country code */
                country?: string;
            };
            header?: never;
            path: {
                /** @description Apple App Store numeric app id */
                app_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_raw_api_v1_reviews__app_id__raw_get: {
        parameters: {
            query?: {
                /** @description ISO 3166-1 alpha-2 country code */
                country?: string;
                /** @description Output format */
                format?: "json" | "csv";
            };
            header?: never;
            path: {
                /** @description Apple App Store numeric app id */
                app_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
